server:
    host: localhost
    port: 8082
    timeout:
        read:  10
        write: 15
        idle:  30

database:
    enabled: false
    type:    sqlite3 # sqlite3, mysql, mssql, postgres
    url:     database.db
